name: CI
<script data-ad-client="ca-pub-9676712284601993" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
